# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='title',
        ),
    ]
