# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20171219_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='starting_time',
            field=models.CharField(max_length=5),
        ),
    ]
