# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20171219_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.CharField(default='Monday', max_length=9),
        ),
    ]
