# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_event_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(default='', max_length=9),
        ),
    ]
